In [1]:
from datascience import *
from path_data_variable import *

In [2]:
english_parts_of_speech = make_array("noun", "pronoun", "verb", "adverb", "adjective", "conjunction", "preposition", "interjection")
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [3]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [4]:
(9/5) * highs + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [5]:
highs.size

4

In [6]:
highs.sum()

57.736000000000004

In [7]:
highs.mean()

14.434000000000001

In [8]:
import numpy as np

In [9]:
np.diff(highs)

array([0.787, 0.198, 0.579])