In [1]:
import numpy as np
from path_data_variable import *

In [2]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [3]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [4]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [5]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

In [6]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

In [7]:
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [8]:
positive_terms = 1 / positive_term_denominators

In [9]:
negative_terms = 1 / (positive_term_denominators + 2)

In [10]:
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955