In [1]:
from datascience import *
import numpy as np
from path_data_variable import *

In [2]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([13.6  , 14.387, 14.585, 15.164])

In [3]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728)
lows

array([2.128, 2.371, 2.874, 3.728])

In [4]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)

array([11.472, 12.016, 11.711, 11.436])

In [5]:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

In [6]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [7]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143